# Generated by Django 4.2.6 on 2023-10-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('cab_type', models.CharField(max_length=20)),
                ('volume', models.FloatField()),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
